# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1202_Sqlite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1202_Sqlite
  pod 'Alamofire'
  pod 'NAMDatabase'

  target '1202_SqliteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1202_SqliteUITests' do
    # Pods for testing
  end

end
