# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1111_ExercicioApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1111_ExercicioApi
  
  target '1111_ExercicioApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1111_ExercicioApiUITests' do
    # Pods for testing
  end
  pod 'Alamofire'
end
