# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1113_TvMazeApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for 1113_TvMazeApi

  target '1113_TvMazeApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1113_TvMazeApiUITests' do
    # Pods for testing
  end

end
