# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1130_MvvmFipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1130_MvvmFipe
  pod 'Alamofire'

  target '1130_MvvmFipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1130_MvvmFipeUITests' do
    # Pods for testing
  end

end
