# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1120_DesafioMvc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for 1120_DesafioMvc

  target '1120_DesafioMvcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1120_DesafioMvcUITests' do
    # Pods for testing
  end

end
